### ISSUE TITLE
Font sizes on iOS seem off

### ISSUE THREAD

**Issue by mit-mit** [gskinnerTeam/flutter-wonderous-app#165] opened 2024-02-01 14:26 UTC
I created some screenshots of a wonder screen with the iOS font size setting screen pasted in on top. It looks like the font size in the app is generally too small compared to the setting?

![IMG_0002](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/13644170/384475e9-9ce9-4612-84c3-575cc66680fb)

 ![IMG_0004](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/13644170/e0af7af0-e6ba-4405-88e1-3aef3caf152e)

**Comment by mit-mit** [comment] 2024-02-01 14:27
cc @jmagman to get her input

**Comment by jmagman** [comment] 2024-02-01 18:28
Looks pretty close? I don't have a preference, seems like a design choice with the custom font and not a bug since it did scale larger.

**Comment by mit-mit** [comment] 2024-02-02 11:42
Here's a better comparison, where I also used a light background from the setting screen.

I can comfortable read the text from the settings screen, but it's very straining for me to read the wonderous text.

<img width="375" alt="IMG_0007" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/13644170/67044d8b-b5cd-4b0a-9220-dc52d0973dab">

**Comment by esDotDev** [comment] 2024-02-05 20:43
Thanks for the report! It does seem like the body text here is noticeably smaller than what is shown as an example in the device settings. 

We do downscale our font sizes a bit on smaller devices to help the UI fit better. Maybe we should exempt the body text to better align with user expectations?

Any thoughts @jaredbell?

**Comment by jaredbell** [comment] 2024-02-07 19:22
@esDotDev  Took a look into this across devices, platforms, etc. — I think the best option is to **remove the concept of scaling down**.

This was a safeguard for older, smaller devices but ultimately affects common/large sized ones as well as it's only looking at device pixel width.

Removing this brings the dynamic type scale back in line which is great for accessibility and user expectations.

We could retain the slight upscaling in place (1.15x-1.25x) as it tends to help fill out the screen a bit more on tablets and desktop/web with larger text/titles and more generous margins.

**Comment by esDotDev** [comment] 2024-02-20 20:30
This has been addressed in v2.2.2 which should be available for download in test-flight. 

@mit-mit The font size should be more like you expect now! Please let us know if this is not the case.

**Closed by esDotDev** 2024-02-20 20:30 UTC

**Comment by mit-mit** [comment] 2024-02-29 17:06
Font size looks great now, thanks!
