### ISSUE TITLE
Some images / pictures not loading in the gallery

### ISSUE THREAD

**Issue by Liedtke** [gskinnerTeam/flutter-wonderous-app#184] opened 2024-07-02 17:16 UTC
Some of the images don't load in the gallery, eg. for the pyramids: [link](https://wonderous.app/web/#/home/wonder/pyramidsGiza?t=1)
Similarly, it seems that all detail views (clicking on the images) do not load, also for pictures where the preview loads fine.

Looking at the console, it seems that these issues are caused by CORS errors:
> Access to XMLHttpRequest at 'https://www.wonderous.info/unsplash/oCkZ6WicY8Q-1200.jpg' from origin 'https://wonderous.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

So wonderous.app seems to try to load these images from wonderous.info which blocks CORS requests.
![image](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/6243569/8634c29b-8f56-4a80-8036-db13cc194ab8)

**Comment by esDotDev** [comment] 2024-07-03 15:02
Thanks for the report, this seems to have been caused by our SSL certificate expiring on the .info domain.

Should be fixed now.

**Closed by esDotDev** 2024-07-03 15:02 UTC
