### ISSUE TITLE
Splashscreen not showing on Android 12 (light mode)

### ISSUE THREAD

**Issue by victorvhpg** [gskinnerTeam/flutter-wonderous-app#15] opened 2022-09-06 00:28 UTC
There are bug on Android 12 (light mode)
Splashscreen not showing

**Comment by X-SLAYER** [comment] 2022-09-08 12:15
I think the problem is that android12 attributes are not mentioned here [flutter_native_splash.yaml](https://github.com/gskinnerTeam/flutter-wonderous-app/blob/master/flutter_native_splash.yaml)
like this : 
```yaml
  android_12:
    image: assets/images/_common/app-logo.png
    icon_background_color: "#272625"
    image_dark: assets/images/_common/app-logo.png
    icon_background_color_dark: "#272625"
```

**Comment by esDotDev** [comment] 2022-09-09 16:56
This should be fixed now?

**Closed** 2022-09-12 18:24 UTC
