### ISSUE TITLE
Native map view sticking to bottom of editorial view

### ISSUE THREAD

**Issue by esDotDev** [gskinnerTeam/flutter-wonderous-app#54] opened 2022-12-08 20:21 UTC
# To Reproduce
- Scroll down on the Editorial View, until the native maps is shown
- Scroll back up to the top
- Notice that the map is still stuck on the bottom of the screen, underneath the tab bar

![image](https://user-images.githubusercontent.com/736973/206559568-08f00043-feee-4e47-b301-7bfd3082826f.png)

**Comment by zanderso** [comment] 2022-12-08 23:14
I think @jonahwilliams has this narrowed down to https://github.com/flutter/flutter/commit/8a7102e7ed7967a7c530ceb904b45e6358d88a11, and we are suspecting that this was introduced in https://github.com/flutter/engine/pull/37394 in that roll. @jonahwilliams is confirming, but I'll cc in @flar preemptively in case this rings any bells. Since the layer state stack change landed a few weeks back, we'd likely need a forward-fix.

**Comment by jonahwilliams** [comment] 2022-12-08 23:21
Confirmed that reverting https://github.com/flutter/engine/pull/37394 fixes the issue on a local build

**Comment by flar** [comment] 2022-12-10 01:30
Fixed in the following engine commit we hope to cherry pick into the next release train.

https://github.com/flutter/flutter/issues/116809

**Closed** 2022-12-19 21:34 UTC
Labels: impeller
